// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW9xlpuy7QFCD_Zo4OI6F-tOO56vx5oss',
    appId: '1:626218538335:web:9fba6f00bbca24d52012ea',
    messagingSenderId: '626218538335',
    projectId: 'instagram-clone-b996a',
    authDomain: 'instagram-clone-b996a.firebaseapp.com',
    storageBucket: 'instagram-clone-b996a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUo5zkarbEqYVxXPF3kGucMKw0AveVWLo',
    appId: '1:626218538335:android:b736a1d5f430d4832012ea',
    messagingSenderId: '626218538335',
    projectId: 'instagram-clone-b996a',
    storageBucket: 'instagram-clone-b996a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE3Maps10tFrZmHQJoEBhMpV-yLxMDQEY',
    appId: '1:626218538335:ios:7a5742e5e93185152012ea',
    messagingSenderId: '626218538335',
    projectId: 'instagram-clone-b996a',
    storageBucket: 'instagram-clone-b996a.appspot.com',
    iosClientId: '626218538335-hv7apt36ef06jj61etprksqgbfm9i0rg.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
